### ISSUE TITLE
crash with WTFOres 1.65 and latest SquidUtils

### ISSUE THREAD

**Issue by dualinfinities** [coolsquid/SquidUtils#46]
Crashes game with no other mods besides dependencies, WTFCore apparently finds a missing hashmap entry but the log cuts off before saying what block it belongs to, like this:
[21:15:47] [Client thread/INFO] [WTFCore]: No hashmap entry found for 

Crash report:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/28/15 9:15 PM
Description: Registering texture

java.lang.NullPointerException: Registering texture
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.collect.StandardTable.put(StandardTable.java:139)
	at com.google.common.collect.HashBasedTable.put(HashBasedTable.java:55)
	at cpw.mods.fml.client.FMLClientHandler.trackBrokenTexture(FMLClientHandler.java:924)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:176)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Possibly involved mods --
Details:

-- Head --
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.collect.StandardTable.put(StandardTable.java:139)
	at com.google.common.collect.HashBasedTable.put(HashBasedTable.java:55)
	at cpw.mods.fml.client.FMLClientHandler.trackBrokenTexture(FMLClientHandler.java:924)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:176)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/blocks.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1702448432 bytes (1623 MB) / 2112618496 bytes (2014 MB) up to 3186360320 bytes (3038 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx3g -XX:PermSize=1024m -Xincgc -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+CMSIncrementalMode
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	SquidAPI{1.1.14} [SquidAPI] (SquidAPI-1.1.15.jar) 
	UCHIJA	SquidUtils{2.1.3} [SquidUtils] (SquidUtils-2.1.4.jar) 
	UCHIJA	WTFCore{1.65} [WhiskyTangoFox's Core] (WTFCore-1.7.10_v1.65.jar) 
	UCHIJA	WTFOres{1.45} [WhiskyTangoFox's Ores] (WTFOres-1.7.10v1.45.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: ASUS EAH6450 Series GL version 4.3.12618 Compatibility Profile Context 13.251.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by coolsquid** [comment]
Should be fixed with the 1.9 rewrite.
